/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import java.util.ArrayList;
import proyecto_final.Clases.Comidas_Clase;
import proyecto_final.Clases.noticias;

/**
 *
 * @author Erick
 */
public class Admin_Interfaz_Inicio extends javax.swing.JFrame {
    
    public static ArrayList<Comidas_Clase> listaComida=new ArrayList<>();
    

    /**
     * Creates new form Admin_Interfaz_Inicio
     */
    public Admin_Interfaz_Inicio() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        titulo = new javax.swing.JLabel();
        bot_usuario = new javax.swing.JButton();
        bot_frases = new javax.swing.JButton();
        bot_comida = new javax.swing.JButton();
        bot_noticias = new javax.swing.JButton();
        panelRound1 = new proyecto_final.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, 40));

        bot_usuario.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        bot_usuario.setText("usuario");
        bot_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bot_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bot_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 200, 70));

        bot_frases.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        bot_frases.setText("frases");
        bot_frases.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bot_frases, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 200, 60));

        bot_comida.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        bot_comida.setText("comida");
        bot_comida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bot_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_comidaActionPerformed(evt);
            }
        });
        getContentPane().add(bot_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, 60));

        bot_noticias.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        bot_noticias.setText("noticias");
        bot_noticias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bot_noticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_noticiasActionPerformed(evt);
            }
        });
        getContentPane().add(bot_noticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 200, 60));

        panelRound1.setBackground(new java.awt.Color(44, 44, 59));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADMIN");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
        panelRound1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 305, 28));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Imagenes/Logo_conCirculo-removebg-preview (2).png"))); // NOI18N
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 330, 250));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Imagenes/boton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 0, 30, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Imagenes/1003541_1.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_noticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_noticiasActionPerformed
        Noticias noti = new Noticias();
        noti.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_bot_noticiasActionPerformed

    private void bot_comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_comidaActionPerformed
        // TODO add your handling code here:
        Comidas noti = new Comidas();
        noti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_comidaActionPerformed

    private void bot_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_usuarioActionPerformed
            AdminUsuario newFrame = new AdminUsuario();
             newFrame.setVisible(true);
             this.dispose();
             newFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_bot_usuarioActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Interfaz_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_comida;
    private javax.swing.JButton bot_frases;
    private javax.swing.JButton bot_noticias;
    private javax.swing.JButton bot_usuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator4;
    private proyecto_final.PanelRound panelRound1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
