/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import javax.swing.JOptionPane;
import proyecto_final.Clases.Clase_Registrarse;
import static proyecto_final.Login.Lista;

/**
 *
 * @author Erick
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();

        this.setLocationRelativeTo(null);

    }

    //sssd
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejemplo = new proyecto_final.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelRound1 = new proyecto_final.PanelRound();
        panelRound2 = new proyecto_final.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Activo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Medio = new javax.swing.JRadioButton();
        Sedentario = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Peso = new javax.swing.JTextField();
        Edad = new javax.swing.JSpinner();
        Altura = new javax.swing.JTextField();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ejemplo1 = new proyecto_final.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldBajar = new javax.swing.JTextField();
        jTextFieldMantener = new javax.swing.JTextField();
        jTextFieldSubir = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        ejemplo.setBackground(new java.awt.Color(70, 86, 132));
        ejemplo.setRoundBottomLeft(30);
        ejemplo.setRoundBottomRight(30);
        ejemplo.setRoundTopLeft(30);
        ejemplo.setRoundTopRight(30);
        ejemplo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("REGISTRARSE");
        ejemplo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 40));

        jLabel16.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Altura en CM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelRound1.setBackground(new java.awt.Color(44, 44, 59));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(71, 71, 132));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Calculadora Fitness");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Imagenes/boton.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 50));

        jLabel7.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peso en Kg:");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        Activo.setBackground(new java.awt.Color(70, 86, 132));
        Activo.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        Activo.setForeground(new java.awt.Color(255, 255, 255));
        Activo.setText("Activo");
        panelRound1.add(Activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Calorias Para Subir de Peso");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        Medio.setBackground(new java.awt.Color(70, 86, 132));
        Medio.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        Medio.setForeground(new java.awt.Color(255, 255, 255));
        Medio.setText("Medio");
        Medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedioActionPerformed(evt);
            }
        });
        panelRound1.add(Medio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        Sedentario.setBackground(new java.awt.Color(70, 86, 132));
        Sedentario.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        Sedentario.setForeground(new java.awt.Color(255, 255, 255));
        Sedentario.setText("Sedentario");
        Sedentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedentarioActionPerformed(evt);
            }
        });
        panelRound1.add(Sedentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Actividad:");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 260, 400, -1));

        jLabel9.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Edad:");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        Peso.setBackground(new java.awt.Color(70, 86, 132));
        Peso.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 14)); // NOI18N
        Peso.setForeground(new java.awt.Color(255, 255, 255));
        Peso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Peso.setCaretColor(new java.awt.Color(255, 255, 255));
        Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoActionPerformed(evt);
            }
        });
        Peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PesoKeyTyped(evt);
            }
        });
        panelRound1.add(Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 30));

        Edad.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        Edad.setModel(new javax.swing.SpinnerNumberModel(14, 14, 70, 1));
        Edad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EdadStateChanged(evt);
            }
        });
        Edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdadMouseClicked(evt);
            }
        });
        panelRound1.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 70, 30));

        Altura.setBackground(new java.awt.Color(70, 86, 132));
        Altura.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 14)); // NOI18N
        Altura.setForeground(new java.awt.Color(255, 255, 255));
        Altura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Altura.setCaretColor(new java.awt.Color(255, 255, 255));
        Altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AlturaKeyTyped(evt);
            }
        });
        panelRound1.add(Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 160, 30));

        Masculino.setBackground(new java.awt.Color(70, 86, 132));
        Masculino.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        Masculino.setForeground(new java.awt.Color(255, 255, 255));
        Masculino.setText("Masculino");
        panelRound1.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        Femenino.setBackground(new java.awt.Color(70, 86, 132));
        Femenino.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        Femenino.setForeground(new java.awt.Color(255, 255, 255));
        Femenino.setText("Femenino");
        Femenino.setToolTipText("");
        panelRound1.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, -1));

        jLabel11.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Genero:");
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Altura en CM");
        panelRound1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Calorias Para Mantener mi Peso");
        panelRound1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        ejemplo1.setBackground(new java.awt.Color(92, 104, 137));
        ejemplo1.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        ejemplo1.setRoundBottomLeft(30);
        ejemplo1.setRoundBottomRight(30);
        ejemplo1.setRoundTopLeft(30);
        ejemplo1.setRoundTopRight(30);
        ejemplo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Calcular");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        ejemplo1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 80, 20));

        panelRound1.add(ejemplo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 330, 110, 40));

        jTextFieldBajar.setEditable(false);
        jTextFieldBajar.setBackground(new java.awt.Color(70, 86, 132));
        jTextFieldBajar.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTextFieldBajar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBajar.setBorder(null);
        jTextFieldBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBajarActionPerformed(evt);
            }
        });
        panelRound1.add(jTextFieldBajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 110, -1));

        jTextFieldMantener.setEditable(false);
        jTextFieldMantener.setBackground(new java.awt.Color(70, 86, 132));
        jTextFieldMantener.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTextFieldMantener.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldMantener.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMantener.setBorder(null);
        panelRound1.add(jTextFieldMantener, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 110, -1));

        jTextFieldSubir.setEditable(false);
        jTextFieldSubir.setBackground(new java.awt.Color(70, 86, 132));
        jTextFieldSubir.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTextFieldSubir.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSubir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSubir.setBorder(null);
        panelRound1.add(jTextFieldSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 110, -1));

        jLabel17.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Calorias Para Bajar de Peso");
        panelRound1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));
        panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 420, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRound1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 40, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Imagenes/atras_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void EdadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EdadStateChanged
        // TODO add your handling code here:

        int edadSeleccionada = (int) Edad.getValue();

        // Verificar si la edad está dentro del rango permitido
        if (edadSeleccionada < 14 || edadSeleccionada > 70) {
            // Mostrar un mensaje de error o tomar la acción correspondiente
            JOptionPane.showMessageDialog(this, "La edad debe estar entre 14 y 70 años", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // La edad está dentro del rango permitido, realizar las acciones necesarias
            // ...
        }
    }//GEN-LAST:event_EdadStateChanged

    private void EdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdadMouseClicked
        int edadSeleccionada = (int) Edad.getValue();

        // Verificar si la edad está dentro del rango permitido
        if (edadSeleccionada < 14 || edadSeleccionada > 70) {
            // Mostrar un mensaje de error o tomar la acción correspondiente
            JOptionPane.showMessageDialog(this, "La edad debe estar entre 14 y 70 años", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // La edad está dentro del rango permitido, realizar las acciones necesarias
            // ...
        }
    }//GEN-LAST:event_EdadMouseClicked

    private void PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoActionPerformed

    private void PesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesoKeyTyped

        char c = evt.getKeyChar();

        // Verificar si el carácter ingresado es un dígito o un punto decimal
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Consumir el evento para evitar que se ingrese el carácter no válido
        }

        // Verificar la longitud total y la posición del punto decimal
        String text = Peso.getText();
        if (text.contains(".")) {
            int dotIndex = text.indexOf('.');
            // Permitir solo un punto decimal y un máximo de 2 decimales después del punto
            if (text.length() - dotIndex > 2) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_PesoKeyTyped

    private void MedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedioActionPerformed

    private void AlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AlturaKeyTyped
        char c = evt.getKeyChar();

        // Verificar si el carácter ingresado es un dígito o un punto decimal
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Consumir el evento para evitar que se ingrese el carácter no válido
        }

        // Verificar la longitud total y la posición del punto decimal
        String text = Altura.getText();
        if (text.contains(".")) {
            int dotIndex = text.indexOf('.');
            // Permitir solo un punto decimal y un máximo de 2 decimales después del punto
            if (text.length() - dotIndex > 2) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_AlturaKeyTyped

    private void SedentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SedentarioActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:

        Clase_Registrarse nuevoRegistro = new Clase_Registrarse();

// Validar si algunos campos esenciales están vacíos o no seleccionados
        if (Edad.getValue() == null || Peso.getText().isEmpty()
                || Altura.getText().isEmpty() || (!Activo.isSelected() && !Medio.isSelected() && !Sedentario.isSelected())
                || (!Femenino.isSelected() && !Masculino.isSelected())) {
            // Mostrar un mensaje de advertencia y salir del método
            JOptionPane.showMessageDialog(this, "Completa todos los campos antes de guardar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Validar la edad en el rango de 14 a 80
        int edadValue = (int) Edad.getValue();
        if (edadValue < 14 || edadValue > 80) {
            // Mostrar un mensaje de error y salir del método
            JOptionPane.showMessageDialog(this, "La edad debe estar en el rango de 14 a 80.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double pesoValue = Double.parseDouble(Peso.getText());
            double alturaValue = Double.parseDouble(Altura.getText());

            // Validar que peso y altura sean valores positivos
            if (pesoValue <= 0 || alturaValue <= 0) {
                JOptionPane.showMessageDialog(this, "El peso y la altura deben ser valores positivos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            nuevoRegistro.setEdad(edadValue);
            nuevoRegistro.setPeso(pesoValue);
            nuevoRegistro.setAltura(alturaValue);

            if (Activo.isSelected()) {
                nuevoRegistro.setActividad("Activo");
            } else if (Medio.isSelected()) {
                nuevoRegistro.setActividad("Medio");
            } else if (Sedentario.isSelected()) {
                nuevoRegistro.setActividad("Sedentario");
            }

            if (Femenino.isSelected()) {
                nuevoRegistro.setGenero("Femenino");
            } else if (Masculino.isSelected()) {
                nuevoRegistro.setGenero("Masculino");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa valores numéricos válidos para peso y altura.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//------------------------------------------------------------------------------------------------------------------------------
        double altura = Double.parseDouble(Altura.getText()); // en cm
        double peso = Double.parseDouble(Peso.getText()); // en kg
        int edad = (int) Edad.getValue();
        String genero = (Femenino.isSelected()) ? "Femenino" : "Masculino";
        String actividad = (Activo.isSelected()) ? "Activo" : (Medio.isSelected()) ? "Medio" : "Sedentario";

// Definir factores de actividad
        double factorActividad;
        switch (actividad) {
            case "Activo":
                factorActividad = 1.725; // Factor alto
                break;
            case "Medio":
                factorActividad = 1.55; // Factor medio
                break;
            default:
                factorActividad = 1.2; // Factor sedentario
        }

// Calcular el requerimiento calórico según el género
        double requerimientoCalorico;
        
        
        if (genero.equals("Femenino")) {
            requerimientoCalorico = (66 + (13.7 * peso)) + ((5 * altura) - (6.8 * edad)) * factorActividad - 200;
        } else { // asumimos que el género es "Masculino"
            requerimientoCalorico = (66 + (13.7 * peso)) + ((5 * altura) - (6.8 * edad)) * factorActividad;
        }

// Calcular calorías para mantener, subir y definir
        double caloriasMantenimiento = Math.round(requerimientoCalorico);
        double caloriasSubir = Math.round(requerimientoCalorico + 500); // Ajusta según tus objetivos
        double caloriasDefinir = Math.round(requerimientoCalorico - 300); // Ajusta según tus objetivos

// Mostrar resultados en un JFrame (puedes ajustar esta parte según tu implementación)
        jTextFieldMantener.setText(caloriasMantenimiento + " kcal");
        jTextFieldSubir.setText(caloriasSubir + " kcal");
        jTextFieldBajar.setText(caloriasDefinir + " kcal");
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jTextFieldBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBajarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextFieldBajarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        
         Persona_Interfaz_Inicio ventanaLogin = new Persona_Interfaz_Inicio();  // Reemplaza con el nombre correcto de tu clase de inicio de sesión
        ventanaLogin.setVisible(true);

        // Cierra la ventana actual
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Activo;
    private javax.swing.JTextField Altura;
    private javax.swing.JSpinner Edad;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JRadioButton Medio;
    private javax.swing.JTextField Peso;
    private javax.swing.JRadioButton Sedentario;
    private proyecto_final.PanelRound ejemplo;
    private proyecto_final.PanelRound ejemplo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldBajar;
    private javax.swing.JTextField jTextFieldMantener;
    private javax.swing.JTextField jTextFieldSubir;
    private proyecto_final.PanelRound panelRound1;
    private proyecto_final.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
